/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 */
public class jfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jmenInicioSesion = new javax.swing.JMenuItem();
        jmenCerrarSesion = new javax.swing.JMenuItem();
        jmenSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenVerSitios = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmenRepIngresos = new javax.swing.JMenuItem();
        jmenRepReserva = new javax.swing.JMenuItem();
        jmenRepFactura = new javax.swing.JMenuItem();
        jmenRepSitios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmenClientes = new javax.swing.JMenuItem();
        jmenUsuarios = new javax.swing.JMenuItem();
        jmenPrecios = new javax.swing.JMenuItem();
        jmenSitios = new javax.swing.JMenuItem();
        jmenVehiculos = new javax.swing.JMenuItem();
        jmenGenerarSitios = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu5.setText("Sistema");

        jmenInicioSesion.setText("Iniciar sesión");
        jMenu5.add(jmenInicioSesion);

        jmenCerrarSesion.setText("Cerrar sesion");
        jMenu5.add(jmenCerrarSesion);

        jmenSalir.setText("Salir del programa");
        jMenu5.add(jmenSalir);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Gestionar");

        jmenVerSitios.setText("Ver sitios");
        jMenu2.add(jmenVerSitios);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Reportes");

        jmenRepIngresos.setText("Ingresos");
        jMenu7.add(jmenRepIngresos);

        jmenRepReserva.setText("Reservas");
        jMenu7.add(jmenRepReserva);

        jmenRepFactura.setText("Facturas");
        jMenu7.add(jmenRepFactura);

        jmenRepSitios.setText("Sitios");
        jMenu7.add(jmenRepSitios);

        jMenuBar1.add(jMenu7);

        jMenu1.setText("Administrar");

        jmenClientes.setText("Clientes");
        jMenu1.add(jmenClientes);

        jmenUsuarios.setText("Usuarios");
        jMenu1.add(jmenUsuarios);

        jmenPrecios.setText("Precios");
        jMenu1.add(jmenPrecios);

        jmenSitios.setText("Sitios");
        jMenu1.add(jmenSitios);

        jmenVehiculos.setText("Vehiculos");
        jMenu1.add(jmenVehiculos);

        jmenGenerarSitios.setText("GenerarSitios");
        jMenu1.add(jmenGenerarSitios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jmenCerrarSesion;
    public javax.swing.JMenuItem jmenClientes;
    public javax.swing.JMenuItem jmenGenerarSitios;
    public javax.swing.JMenuItem jmenInicioSesion;
    public javax.swing.JMenuItem jmenPrecios;
    public javax.swing.JMenuItem jmenRepFactura;
    public javax.swing.JMenuItem jmenRepIngresos;
    public javax.swing.JMenuItem jmenRepReserva;
    public javax.swing.JMenuItem jmenRepSitios;
    public javax.swing.JMenuItem jmenSalir;
    public javax.swing.JMenuItem jmenSitios;
    public javax.swing.JMenuItem jmenUsuarios;
    public javax.swing.JMenuItem jmenVehiculos;
    public javax.swing.JMenuItem jmenVerSitios;
    // End of variables declaration//GEN-END:variables
}
